### ISSUE TITLE
migrate-db job issues

### ISSUE THREAD

**Issue by bonickle** [sonatype/nexus-iq-server-ha#31]
migrate-db jobs runs every-time helm deploy is ran for this helm chart and requires us to manually scale down the IQ pods in order for it not to fail. The migrate-db job should handle that for us, it is a very tedious process to automate/manually scale down those pods ourselves so that job can pass preventing a failed deploy.

**Comment by snakebyte91** [comment]
The job is also not GitOps ready. Argo recreates the job in an endless loop.

**Comment by snakebyte91** [comment]
Please add the annotations:

```
helm.sh/hook: pre-install,pre-upgrade
helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
```

to the `migrate-db` job. This would prevent argo from re-creating the job.

The scale down of the pods is also a pain with argo. We have to remove the nexus iq server application from argo, perform several steps and after the job ran successfull, argo can manage the app again.
